services:
  frontend:
    build:
      context: .
      dockerfile: docker/production/Dockerfile.prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - /app/node_modules
      - /app/.next
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  whisper-backend:
    ports:
      - "9001:9000"  # Expose ASR service to host
    volumes:
      - ./.secrets:/app/.secrets:ro  # Mount secrets file read-only
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
