version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/development/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

  whisper-backend:
    ports:
      - "9000:9000"  # Expose for debugging in development
