services:
  frontend:
    build:
      context: .
      dockerfile: docker/development/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

  whisper-backend:
    # No ports exposed to host - only accessible via internal network
    # Use docker logs to debug if needed: docker compose logs whisper-backend
