services:
  frontend:
    build:
      context: .
      dockerfile: docker/production/Dockerfile.prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - /app/node_modules
      - /app/.next
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  whisper-backend:
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
