services:
  frontend:
    build:
      context: ..
      dockerfile: docker/production/Dockerfile.prod
    container_name: asr-frontend
    ports:
      - "9001:3000"
    environment:
      - NODE_ENV=production
      - WHISPER_API_URL=http://whisper-backend:9000
      - WHISPER_MODEL=${WHISPER_MODEL:-base}
      - WHISPER_DEFAULT_LANGUAGE=${WHISPER_DEFAULT_LANGUAGE:-en}
      - SUPPORTED_LANGUAGES=${SUPPORTED_LANGUAGES:-en,it,fr,es,de}
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:9001
    restart: unless-stopped
    volumes:
      - /app/node_modules
      - /app/.next
      - /home/bob/code/asr-server/.secrets:/app/.secrets:ro
    depends_on:
      - whisper-backend
    networks:
      - whisper-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  whisper-backend:
    image: onerahmet/openai-whisper-asr-webservice:latest
    container_name: whisper-backend
    # No ports exposed to host - only accessible via internal network
    environment:
      - ASR_MODEL=${WHISPER_MODEL:-base}
      - ASR_ENGINE=openai_whisper
    volumes:
      - whisper-models:/root/.cache/whisper
    networks:
      - whisper-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

volumes:
  whisper-models:

networks:
  whisper-network:
    driver: bridge
